server:
  port: 8080
  servlet:
    session:
      timeout: 30m
      cookie:
        secure: false

spring:
  profiles:
    active: local

  application:
    name: booking-service

  jpa:
    open-in-view: false

service:

  # WALK
  # Период проверки прогулок для перевода в статус BOOKING_FINISHED в формате cron
  checkWalkToCompleteBooking: "0 */15 * * * *"
  # Период проверки прогулки для перевода в статус FINISHED в формате cron
  checkWalksToFinish: "30 */30 * * * *"
  # Крайнее время бронирования до начала прогулки в минутах
  walkInBookingStatusDeadLine: 120

  # BOOKING
  # Время жизни бронирования без оплаты в минутах
  bookingLifeTime: 15
  # Период проверки бронирований в секундах
  bookingCheckPeriod: 5
  # Период проверки оплаты в секундах
  invoiceCheckPeriod: 5

  # DISCOUNT
  # Период проверки истекших ваучеров
  checkVouchersToExpired: "0 */5 * * * *"

  # Активировать скидку для групп
  groupDiscountEnabled: true
  # Процент скидки для групп
  groupDiscountValuePercent: 15
  # Абсолютное значение скидки для групп
  groupDiscountValueAbsolute: 0
  # Минимальный размер группы
  groupDiscountMinPlaces: 5

  # Активировать скидку для повторных бронирований
  repeatedBookingDiscountEnabled: true
  # Процент скидки для повторных бронирований
  repeatedBookingDiscountPercent: 15
  # Абсолютное значение скидки для повторных бронирований
  repeatedBookingDiscountAbsolute: 0

logging:
  config: config/logback.xml