server:
  port: 8088
spring:
  autoconfigure:
    exclude:
  #      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  #      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: false
    hibernate.ddl-auto: none

logging:
  level:
    web: DEBUG

service:
  bookingLifeTime: 1
  bookingCheckPeriodImMs: 5000
  invoiceCheckPeriodImMs: 5000