server:
  port: 8080
spring:
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: false
    hibernate.ddl-auto: none

  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com:
      samoylenko:
        bookingservice:
          service: DEBUG